- type: job
  id: Prisoner
  name: job-name-prisoner
  description: job-description-prisoner
  playTimeTracker: Prisoner
  experienceDefinition: NoSpecialRoleExperience
  icon: "JobIconPrisoner"
  canBeAntag: true
