- type: job
  id: BlueShield
  name: job-name-blueshield
  description: job-description-blueshield
  playTimeTracker: JobBlueShield
  requirements:
    - !type:DepartmentTimeRequirement
      department: Security
      time: 72000
    - !type:DepartmentTimeRequirement
      department: Medical
      time: 72000
    - !type:OverallPlaytimeRequirement
      time: 180000
    - !type:SpeciesRequirement
      inverted: true
      species:
      - Felinid
  startingGear: BlueShieldGear
  icon: "JobIconBlueShield"
  supervisors: job-supervisors-centcom
  canBeAntag: false
  access:
  - Command
  - Bar
  - Service
  - Maintenance
  - Janitor
  - Theatre
  - Kitchen
  - Chapel
  - Hydroponics
  - External
  - Cryogenics
  - Chemistry
  - Engineering
  - Research
  - Detective
  - Salvage
  - Security
  - Brig
  - Lawyer
  - Cargo
  - Atmospherics
  - Cargo
  - Medical
  - Blueshield
  - Paramedic
  - Clown
  - Librarian
  - Psychologist
  - Reporter
  - Mime
  - Musician
  special:
  - !type:AddImplantSpecial
    implants: [ MindShieldImplant ]
  - !type:AddComponentSpecial
    components:
    - type: DefibrillatorSkill

- type: startingGear
  id: BlueShieldGear
  equipment:
    id: BlueShieldPDA
    ears: ClothingHeadsetBlueShield
    pocket1: WeaponPistolMk58Nonlethal
    gloves: ClothingHandsGlovesCombat
  storage:
    back:
    - Stunbaton
    - Flash
    - MagazinePistolRubber
    - MagazinePistol

- type: chameleonOutfit
  id: BlueShieldChameleonOutfit
  job: BlueShield
  hasMindShield: true
  equipment:
    eyes: ClothingEyesGlassesBlueShield
    head: ClothingHeadHatBeretSecurity
    mask: BlueShieldGasMask
    neck: ClothingBeltHolster
    gloves: ClothingHandsGlovesCombat
