- type: job
  id: AggressiveAnimals
  name: job-name-aggressive-animals
  description: job-description-aggressive-animals
  experienceDefinition: NoExperience
  playTimeTracker: AntahAggressiveAnimals
  requirements:
  - !type:OverallPlaytimeRequirement
    time: 20h

- type: job
  id: SpaceDragon
  name: job-name-space-dragon
  description: job-description-space-dragon
  playTimeTracker: AntagSpaceDragon
  experienceDefinition: NoExperience
  requirements:
  - !type:OverallPlaytimeRequirement
    time: 20h



