- type: job
  id: DerelictBorg # just imagine here joke pls
  name: job-name-derelict-borg
  description: job-description-derelict-borg
  experienceDefinition: DerelictBorgRoleExperience
  setPreference: false
  playTimeTracker: JobDerelictBorg
  requirements:
  - !type:OverallPlaytimeRequirement
    time: 10h
