# Â© SS220, An EULA/CLA with a hosting restriction, full text: https://raw.githubusercontent.com/SerbiaStrong-220/space-station-14/master/CLA.txt

- type: job
  id: MiGo
  name: job-name-migo
  description: job-description-migo
  playTimeTracker: CultistOfYogg
  antagonist: true
  requirements:
  - !type:OverallPlaytimeRequirement
    time: 20h
