- type: job
  id: SeniorEngineer
  name: job-name-senior-engineer
  description: job-description-senior-engineer
  playTimeTracker: JobSeniorEngineer
  requirements:
    - !type:RoleTimeRequirement
      role: JobAtmosphericTechnician
      time: 43200 #12 hrs
    - !type:RoleTimeRequirement
      role: JobStationEngineer
      time: 43200 #12 hrs
    - !type:DepartmentTimeRequirement
      department: Engineering
      time: 216000 # 60 hrs
  startingGear: SeniorEngineerGear
  experienceDefinition: SeniorEngineerRoleExperience
  icon: "JobIconSeniorEngineer"
  supervisors: job-supervisors-ce
  access:
  - Maintenance
  - Engineering
  - External
  - Atmospherics
  special:
  - !type:AddComponentSpecial
    components:
    - type: MentorRole
      teachInfo:
        Construction:
          multiplier: 1.5
          maxBuffSkillLevel: 3

- type: startingGear
  id: SeniorEngineerGear
  equipment:
    id: SeniorEngineerPDA
    eyes: ClothingEyesGlassesMeson
    belt: ClothingBeltUtilityEngineering
    ears: ClothingHeadsetEngineering

- type: chameleonOutfit
  id: SeniorEngineerChameleonOutfit
  job: SeniorEngineer
  equipment:
    head: ClothingHeadHatHardhatYellow
    mask: ClothingMaskBreath
    neck: ClothingNeckScarfStripedOrange
    outerClothing: ClothingOuterWinterEngi
    gloves: ClothingHandsGlovesColorYellow
    shoes: ClothingShoesBootsMag
