- type: job
  id: SeniorPhysician
  name: job-name-senior-physician
  description: job-description-senior-physician
  playTimeTracker: JobSeniorPhysician
  requirements:
    - !type:RoleTimeRequirement
      role: JobChemist
      time: 43200 #12 hrs
    - !type:RoleTimeRequirement
      role: JobMedicalDoctor
      time: 43200 #12 hrs
    - !type:DepartmentTimeRequirement
      department: Medical
      time: 216000 # 60 hrs
  startingGear: SeniorPhysicianGear
  experienceDefinition: SeniorPhysicianRoleExperience
  icon: "JobIconSeniorPhysician"
  supervisors: job-supervisors-cmo
  access:
  - Medical
  - Maintenance
  - Chemistry
  special:
  - !type:AddComponentSpecial
    components:
    - type: MentorRole
      teachInfo:
        Medicine:
          multiplier: 1.5
          maxBuffSkillLevel: 3

- type: startingGear
  id: SeniorPhysicianGear
  equipment:
    id: SeniorPhysicianPDA
    ears: ClothingHeadsetMedical
    belt: ClothingBeltMedicalFilled

- type: chameleonOutfit
  id: SeniorPhysicianChameleonOutfit
  job: SeniorPhysician
  equipment:
    head: ClothingHeadHatBeretMedic
    eyes: ClothingEyesHudMedical
    mask: ClothingMaskSterile
    outerClothing: ClothingOuterCoatLab
    gloves: ClothingHandsGlovesLatex
