# © SS220, An EULA/CLA with a hosting restriction, full text: https://raw.githubusercontent.com/SerbiaStrong-220/space-station-14/master/CLA.txt

- type: entity
  name: Оперативник ГСН
  id: CentCommOperativeSRT
  components:
    - type: Sprite
      sprite: SS220/Markers/jobs.rsi
      state: centcommoperativebs
    - type: RandomHumanoidSpawner
      settings: CentCommOperativeSRT

- type: randomHumanoidSettings
  id: CentCommOperativeSRT
  speciesBlacklist: [ Arachnid, Diona, Dwarf, Reptilian, Skeleton, SlimePerson, Vox, Moth, Felinid, Tajaran]
  components:
    - type: RandomHumanoidAppearance
      randomizeName: false
      hair: HairBald
    - type: RandomMetadata
      nameSegments:
        - NamesFirstSRTMember
        - NamesLastSRTMember
    - type: MindShield
    - type: GhostRole
      name: ghost-role-information-centcom-srt-name
      description: ghost-role-information-centcom-srt-description
    - type: GhostTakeoverAvailable
    - type: Loadout
      prototypes: [ CentcomOperativeSRTGear ]

- type: playTimeTracker
  id: JobCentcommOperativeSRT

- type: job
  id: CentcomOperativeSRT
  name: job-name-cc-srt-operative
  description: job-description-centcomoff
  setPreference: false
  startingGear: CentcomOperativeSRTGear
  playTimeTracker: JobCentcommOperativeSRT
  icon: "JobIconNanotrasen"
  supervisors: job-supervisors-centcom
  canBeAntag: false
  radioBold: true
  accessGroups:
  - AllAccess
  access:
  - CentralCommandSRT
  - CentralCommand
  special:
  - !type:AddComponentSpecial
    components:
    - type: DefibrillatorSkill

- type: startingGear
  id: CentcomOperativeSRTGear
  equipment:
    jumpsuit: ClothingUniformJumpsuitSRTOperative
    shoes: ClothingShoesBootsBlueShieldJackFilled
    head: ClothingHeadBeretBlueshield
    eyes: ClothingEyesGlassesBallisticBlueShield
    mask: ClothingMaskNeckGaiter
    neck: ClothingNeckCloakCape
    gloves: ClothingHandsGlovesPowergloveDisabler
    outerClothing: ClothingOuterArmorBlueShieldBulletproof
    id: CentcomOperativeSRTPDA
    ears: ClothingHeadsetAltCentComm
    pocket1: WeaponEnergyGunRevolverSelfRecharger
    pocket2: TelescopicShield
    belt: ClothingBeltBlueShieldFilled
    back: ClothingBackpackBlueShieldHightFilled
