- type: job
  id: DeathsquadCommander
  name: job-name-dq-commander
  description: job-description-deathsquad
  playTimeTracker: JobDeathSquadCommander
  setPreference: false
  startingGear: DeathSquadLeaderGear
  experienceDefinition: DeathSquadRoleExperience
  icon: "JobIconDeathsquadCommander"
  supervisors: job-supervisors-centcom
  canBeAntag: false
  accessGroups:
  - AllAccess
  - CentralCommand

- type: job
  id: DeathsquadHealer
  name: job-name-dq-specialist
  description: job-description-deathsquad
  playTimeTracker: JobDeathSquadHealer
  setPreference: false
  startingGear: DeathSquadHealerGear
  experienceDefinition: DeathSquadRoleExperience
  icon: "JobIconDeathsquadHealer"
  supervisors: job-supervisors-centcom
  canBeAntag: false
  accessGroups:
  - AllAccess
#  access: #SS220-DeathSquad Update
  - CentralCommand
