- type: job
  id: CBURN
  name: job-name-cburn
  description: job-description-cburn
  playTimeTracker: JobCBURN
  setPreference: false
  startingGear: CBURNGear
  experienceDefinition: CBURNRoleExperience # SS220-experience
  icon: "JobIconNanotrasen"
  supervisors: job-supervisors-centcom
  canBeAntag: false
  accessGroups:
  - AllAccess
  access:
  - CentralCommand
  - CentralCommandCBURN # SS220 centcomm access fix
  departmentsToIgnoreInTitles: # SS220 Round End Titles
  - Command                    # SS220 Round End Titles
  special:
  - !type:AddImplantSpecial
    implants: [ MindShieldImplant, DeathRattleImplantCentcomm ]
  # SS220-playtime-restrictions-begin
  requirements:
    - !type:DepartmentTimeRequirement
      department: Security
      time: 20h
  # SS220-playtime-restrictions-begin

- type: startingGear
  id: CBURNGear
  equipment:
    jumpsuit: ClothingUniformJumpsuitColorBrown
    back: ClothingBackpackDuffelCBURN
    mask: ClothingMaskGasERT
    eyes: ClothingEyesGlassesSecurity
    ears: ClothingHeadsetAltCentCom
    gloves: ClothingHandsGlovesCombat
    outerClothing: ClothingOuterHardsuitCBURN
    shoes: ClothingShoesBootsCombatFilled
    id: CBURNPDA
    pocket1: HandheldRadio #SS220 Radio
    pocket2: WeaponLaserGun
    belt: ClothingBeltBandolier
  storage:
    back:
    - WeaponShotgunDoubleBarreled
    - BoxShotgunIncendiary
    - GrenadeFlashBang
    - PillAmbuzolPlus
    - PillAmbuzol

- type: chameleonOutfit
  id: CBURNChameleonOutfit
  job: CBURN
  hasMindShield: true
  equipment:
    head: ClothingHeadHelmetCBURN
    neck: ClothingNeckScarfStripedBrown
