- type: job
  id: Visitor
  name: job-name-visitor
  description: job-description-visitor
  playTimeTracker: JobVisitor
  canBeAntag: false
  icon: JobIconVisitor
  experienceDefinition: VisitorRoleExperience # SS220-experience
  setPreference: false
  overrideConsoleVisibility: true
  access:
  - Maintenance
  extendedAccess:
  - External
