- type: job
  id: DeathSquadLeader
  experienceDefinition: DeathSquadRoleExperience
  name: job-name-death-squad-leader
  description: job-description-death-squad-leader
  playTimeTracker: DeathSquadLeader
  requirements:
    - !type:DepartmentTimeRequirement
      department: Security
      time: 20h
    - !type:DepartmentTimeRequirement
      department: Command
      time: 10h

- type: job
  id: DeathSquadHealer
  experienceDefinition: DeathSquadRoleExperience
  name: job-name-death-squad-healer
  description: job-description-death-squad-healer
  playTimeTracker: DeathSquadHealer
  requirements:
    - !type:DepartmentTimeRequirement
      department: Security
      time: 15h
    - !type:DepartmentTimeRequirement
      department: Medical
      time: 10h

- type: job
  id: DeathSquadOperative
  experienceDefinition: DeathSquadRoleExperience
  name: job-name-death-squad-operative
  description: job-description-death-squad-operative
  playTimeTracker: DeathSquadOperative
  requirements:
    - !type:DepartmentTimeRequirement
      department: Security
      time: 15h
